### ISSUE TITLE
Frame processor face_enhancer not found Warning: Failed to load frame processor face_enhancer requested by UI state.

### ISSUE THREAD

**Issue by uladdzerzh** [hacksider/Deep-Live-Cam#1354]
I’m using MacOS 15.5. In terminal I have an output:

Frame processor face_enhancer not found Warning: Failed to load frame processor face_enhancer requested by UI state.

**Comment by Pr3zLy** [comment]
same with me, no problem with the preview using UI but I tried run from terminal and fixed with `--frame-processor face_swapper face_enhancer`

**Comment by AdrLfv** [comment]
Hi. This error comes from load_frame_processor_module() in core.py but the except doesn't show the real error.

Try installing gfpan `pip install gfpgan==1.3.8`. It solved the error for me

**Comment by Clivertf** [comment]
> Hi. This error comes from load_frame_processor_module() in core.py but the except doesn't show the real error.
> 
> Try installing gfpan `pip install gfpgan==1.3.8`. It solved the error for me

It doesn't work. Still gets the same error.

Frame processor face_enhancer not found
Warning: Failed to load frame processor face_enhancer requested by UI state.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\adoma/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\adoma/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\adoma/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\adoma/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\adoma/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[DLC.CORE] Processing...
Frame processor face_enhancer not found
Warning: Failed to load frame processor face_enhancer requested by UI state.

**Comment by hacksider** [comment]
See pinned issue
