### ISSUE TITLE
[ONNXRuntimeError] : 7 : INVALID_PROTOBUF

### ISSUE THREAD

**Issue by Aleksoooxd** [hacksider/Deep-Live-Cam#241]
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "Deep-Live-Cam\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
                                                                                   ^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\venv\Lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "Deep-Live-Cam\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "Deep-Live-Cam\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from User/.insightface\models\buffalo_l\1k3d68.onnx failed:Protobuf parsing failed.

At first i forgot to install ffmpeg so while waiting for it to install i ran the program after I've commented the pre_check line which responds for checking if ffmpeg is installed. It worked fine, besides the fact that i had a black square instead of the face i wantet and it was quite laggy but after a few second i got a blue screen. So now I finally installed ffmpeg and while the "launcher" works just fine the preview obviously doesnt really load as the error would suggest. Anyone had a similar problem/ knows the fix to this issue?

**Comment by William-island** [comment]
May be the models from buffalo_l are damaged? I have the similar problem when using the models downloaded by powershell. I fixed it by directly download the models from the official website.

**Comment by Aleksoooxd** [comment]
Yep, that was it. Still getting a blue screen after couple second though :/

**Comment by Aleksoooxd** [comment]
Figured out the models from buffalo_I are getting damaged after each blue screen. 
STOPCODE: IRQL_NOT_LESS_OR_EQUAL
Source: ntoskrnl.exe

**Comment by luotn** [comment]
I am facing a similliar issue, my output is:
`Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`
The live view is a black screen due to this issue.

**Comment by cyc-hahaha** [comment]
> 我面临一个类似的问题，我的输出是：由于这个问题，实时视图是黑屏。`Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`

me too

**Comment by bunnitech** [comment]
mine was working fine then suddenly stopped working, the live feed halted but the ui was ok. after restarting the ui it gives me this error.

**Comment by PoPzQ** [comment]
I had model files in modules folder(similar, but wrong) (Deep-Live-Cam-main\models is correct, Deep-Live-Cam-main\modules is incorrect)

**Comment by HeischiHSLU** [comment]
> I am facing a similliar issue, my output is: `Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.` The live view is a black screen due to this issue.

Did u find a solution for your Problem im having the same Problem as .

**Comment by hacksider** [comment]
if you get the latest commit, download
https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128.onnx and put it in the models folder
