### ISSUE TITLE
On Mac, running run.py opens a blank window.

### ISSUE THREAD

**Issue by ZeeMenng** [hacksider/Deep-Live-Cam#80]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/063b9d8d-e104-4422-b9aa-b9bd7728a57e">

On Mac, running run.py opens a blank window.

Mac，运行run.py 窗口打开是空白。

**Comment by ryancui92** [comment]
Same. But you can click in the blank, seems it works only missing UI component render

**Comment by ZeeMenng** [comment]
My operating system is macOS 14.4.1 . You're right, although the window appears blank, all the components are clickable. I tried using the live view feature, and it responded—the camera turns on, but the pop-up window still doesn't display.

我的操作系统是MacOS 14.4.1 ，你说的对，虽然窗口上显示空白，但组件都可以点击到，我试着用了实时查看功能，有反应，摄像头会打开，但弹出的子窗口还是看不到人像。

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/2a23d837-3911-4f74-aec9-7ea42d3eea89">

**Comment by caocuong2404** [comment]
The same problem guys

My device info:
- Mac 14.5 Apple M2 Pro
- Python 3.10.14

**Comment by hacksider** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/38 they have the same problem which is already solved

**Comment by ZeeMenng** [comment]
Yes, I reinstalled tcl-tk, reset the environment variables to guide the Python interpreter to the correct version of the Tk library, and then reinstalled Python@3.10. After re-running the installation steps with pip install -r requirements.txt, it worked.

However, it's a bit cumbersome. I hope future installation scripts can directly accommodate macOS systems.

是的，我重新安装了tcl-tk、重新设置环境变量指导 Python 解释器在哪里找到正确版本的 Tk 库、再重新安装Python@3.10，重新执行安装步骤 pip install -r requirements.txt，就可以了。

不过有点麻烦，希望后面可以直接在安装脚本中适配下Mac系统。

<img width="599" alt="image" src="https://github.com/user-attachments/assets/ca4e1989-ebcc-494a-93b9-3ac30f5b1d37">

**Comment by hacksider** [comment]
Good to hear that it is resolved on your end. Sorry but I really don't have any mac so I'm at the mercy of the communities help in everything when it comes to mac issues.

**Comment by hacksider** [comment]
Anyway, since it is resolved. I'm going to close the issue but feel free to reply or start another issue if you encounter one (or feel free to push some codes as well)

**Comment by amaanr** [comment]
Despite reinstalling tcl-tk, resetting environment variables and reinstalling python@3.10, I'm still getting the blank screen. Anyone else find another solution?

**Comment by laloe74** [comment]
> Despite reinstalling tcl-tk, resetting environment variables and reinstalling python@3.10, I'm still getting the blank screen. Anyone else find another solution?

https://stackoverflow.com/a/61879759

**Comment by Mrkomiljon** [comment]
Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\deep-live\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\USER\miniconda3\envs\deep-live\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\ui.py", line 281, in webcam_preview
    source_image = get_one_face(cv2.imread(modules.globals.source_path))
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\USER\Desktop\New_models_2024\Deep-Live-Cam\modules\face_analyser.py", line 14, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=modules.globals.execution_providers)
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

is someone faced like this issue?
