### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by VladSez** [hacksider/Deep-Live-Cam#98]
On MacOS Sonoma inside venv I am getting error when running python run.py:

`ModuleNotFoundError: No module named '_tkinter'`
```
python run.py

Traceback (most recent call last):
  File "/Users/uladzislausazonau/projects/personal/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Users/uladzislausazonau/projects/personal/Deep-Live-Cam/modules/core.py", line 20, in <module>
    import modules.ui as ui
  File "/Users/uladzislausazonau/projects/personal/Deep-Live-Cam/modules/ui.py", line 3, in <module>
    import customtkinter as ctk
  File "/Users/uladzislausazonau/projects/personal/Deep-Live-Cam/myenv/lib/python3.10/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by VladSez** [comment]
resolved with recreating venv environment and reinstalling deps with python 3.10

**Comment by tetsuoo-online** [comment]
> resolved with recreating venv environment and reinstalling deps with python 3.10

Please did you install "deps" ? I already have Python 3.10.11, the venv, and installed all the requirements

**Comment by bbuchalter** [comment]
@VladSez - could you provide more detailed instructions? I followed steps I thought reasonable, but am still getting this error.

My steps after receiving this error:
* Close current terminal
* New terminal, `cd $REPO`
* `rm -rf venv`
* `python3.10 -m venv venv`
* `source venv/bin/activate`
* `pip install -r requirements.txt`
* `python run.py`

**Comment by bbuchalter** [comment]
For macOS, `brew install python-tk@3.10` resolved the issue for me, but resulted in a new one, which may or may not be associated with my solution:
```
Deep-Live-Cam % python run.py                  
Matplotlib is building the font cache; this may take a moment.
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "/Users/brian.buchalter/workspace/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/brian.buchalter/workspace/Deep-Live-Cam/modules/core.py", line 237, in run
    if not pre_check():
  File "/Users/brian.buchalter/workspace/Deep-Live-Cam/modules/core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "/Users/brian.buchalter/workspace/Deep-Live-Cam/modules/core.py", line 166, in update_status
    ui.update_status(message)
  File "/Users/brian.buchalter/workspace/Deep-Live-Cam/modules/ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'
```

**Comment by bbuchalter** [comment]
Based on other discussions in issues like https://github.com/hacksider/Deep-Live-Cam/issues/159, this is associated with missing ffmpeg.

**Comment by VladSez** [comment]
Try to recreate venv with python venv --system-site-packages myenv activate venv and run all other steps

**Comment by kongomongo** [comment]
fwiw I actually had Tcl/Tk support unchecked on install, that's why it didnt work.
